name: Publish Docker image and Deploy to EC2

on:
  push:
    branches: ['main']

jobs:
  # Job to build and push Docker image to Docker Hub
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/Node-JS  # Replace with your Docker Hub repository name
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job to deploy Docker container to EC2 instance
  deploy_to_ec2:
    name: Deploy Docker container to EC2
    runs-on: ubuntu-latest
    needs: push_to_registry  # Make sure deployment happens after the image is pushed
    steps:
      - name: Checkout repository again (if needed on EC2)
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or DNS
          EC2_USER: ${{ secrets.EC2_USER }}  # EC2 username (usually 'ubuntu')
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # SSH private key for EC2 access
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
        run: |
          # Create a private key file from the secret stored in GitHub Actions
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem  # Ensure the private key has the correct permissions

          # SSH to EC2 instance and deploy Docker container
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Pull the Docker image from Docker Hub (ensure to use the correct repository and tag)
            docker pull $DOCKER_USERNAME/Node-JS:latest  # Adjust the image name as per your repo
            
            # Run the Docker container (modify the container name and options as needed)
            docker run -d --name nodejs-container -p 80:80 $DOCKER_USERNAME/Node-JS:latest  # Run the container in detached mode
          EOF
